# Generated by Django 3.0 on 2021-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='cart_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
